version: 2
jobs:
  build:
    working_directory: ~/lakoo-iap-validator
    docker:
      - image: lakoo/node-alpine-gcloud
    environment:
      - PORT: 8080
    steps:
      - checkout
      - run:
          name: Setup gcloud
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 -d > /client-secret.json
            gcloud auth activate-service-account --key-file /client-secret.json
            gcloud config set project $GCLOUD_PROJECT
            rm .gitignore
            echo $IAP_CONFIG | base64 -d > config.js
      - deploy:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              gcloud functions deploy iap-validator --region asia-northeast1 --trigger-http --entry-point app --runtime nodejs8
            fi
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              gcloud functions deploy iap-validator-develop --region asia-northeast1 --trigger-http --entry-point app --runtime nodejs8
            fi
  lint:
    working_directory: ~/lakoo-iap-validator
    docker:
      - image: lakoo/node-alpine-gcloud
    environment:
      - PORT: 8080
    steps:
      - checkout
      - restore_cache:
          key: lakoo-iap-validator-lint-{{ checksum "package.json" }}
      - run:
          name: Prepare configs for test
          command: |
            mv config.js.sample config.js
      - run:
          name: Dependencies
          command: |
            export PATH=${PATH}:"~/lakoo-iap-validator/node_modules/.bin"
            apk add --no-cache curl
            yarn install
      - run:
          name: Lint Test
          command: yarn test
      - run:
          name: Start Test
          command: yarn start
          background: true
      - run:
          name: Curl Test
          command: |
            sleep 5
            curl --retry 10 --retry-delay 5 -v http://localhost:8080/
      - save_cache:
          key: lakoo-iap-validator-lint-{{ checksum "package.json" }}
          paths:
            - "~/.cache/yarn"
workflows:
  version: 2
  lint_and_or_deploy:
    jobs:
      - lint
      - build:
          requires:
            - lint
          filters:
            branches:
              only:
                - develop
                - master
